// src/lib/utils/hashRoutes.js
import { browser } from '$app/environment';
import { base } from '$app/paths';

/**
 * Creates a route URL that works with our current setup
 * @param {string} path - Route path without leading slash (e.g. "map/consciousness")
 * @returns {string} - Properly formatted URL
 */
export function getRoute(path) {
  // Clean up the path first
  const cleanPath = path.startsWith('/') ? path.substring(1) : path;
  
  // For empty path (home), just return base
  if (!cleanPath) return `${base}/`;
  
  // Otherwise return standard path (we've decided not to use hash routing)
  return `${base}/${cleanPath}`;
}

/**
 * Adds language parameter to a route
 * @param {string} route - The route generated by getRoute()
 * @param {string} lang - Language code
 * @returns {string} - Route with language parameter
 */
export function addLangToRoute(route, lang) {
  // Only add lang param if it's not English (default)
  if (!lang || lang === 'en') return route;
  
  // Add query param
  return `${route}${route.includes('?') ? '&' : '?'}lang=${lang}`;
}
