// src/lib/utils/hashRoutes.js
import { browser } from '$app/environment';
import { base } from '$app/paths';

/**
 * Creates a hash-based route URL that works with both development and production
 * @param {string} path - Route path without leading slash (e.g. "map/consciousness")
 * @returns {string} - Properly formatted URL for the environment
 */
export function getRoute(path) {
  // In development, use normal paths
  if (browser && process.env.NODE_ENV === 'development') {
    return `${base}/${path}`;
  }
  
  // In production, use hash-based routing
  return `${base}/#/${path}`;
}

/**
 * Adds language parameter to a route in a way that works with hash routing
 * @param {string} route - The route generated by getRoute()
 * @param {string} lang - Language code
 * @returns {string} - Route with language parameter
 */
export function addLangToRoute(route, lang) {
  // Only add lang param if it's not English (default)
  if (!lang || lang === 'en') return route;
  
  // Check if this is a hash route
  if (route.includes('#/')) {
    // For hash routes, add query param after the hash
    return `${route}?lang=${lang}`;
  } else {
    // For regular routes, add query param normally
    return `${route}${route.includes('?') ? '&' : '?'}lang=${lang}`;
  }
}
