name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: NODE_ENV=production npm run build

      # Make sure the 404.html file is properly handled
      - name: Copy SPA files for GitHub Pages
        run: |
          # Ensure 404.html exists and is setup for SPA routing
          if [ -f "static/404.html" ]; then
            cp static/404.html build/404.html
            echo "Copied 404.html from static directory"
          else
            cp build/index.html build/404.html
            echo "Created 404.html from index.html"
          fi
          
          # Create a .nojekyll file to disable Jekyll processing
          touch build/.nojekyll
          
          # Output build directory contents for debugging
          echo "Build directory contents:"
          ls -la build/
      
      # Create CNAME if needed
      - name: Setup CNAME
        run: |
          if [ -f "static/CNAME" ]; then
            cp static/CNAME build/CNAME
            echo "Copied CNAME file"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
